// ============================================================
// Capability Registry
// Ported from model-engine/registry/capability-registry.js
// ============================================================

export const CAPS = {
  CHAT: 'chat',
  CODE: 'code',
  VISION: 'vision',
  REASONING: 'reasoning',
  LONG_CONTEXT: 'long_context',
  FAST: 'fast',
  EMBEDDING: 'embedding',
  IMAGE_GEN: 'image_gen',
  AUDIO: 'audio',
  FUNCTION: 'function_calling',
  FREE: 'free_tier',
} as const;

export type Cap = typeof CAPS[keyof typeof CAPS];

export type TaskType =
  'research' | 'reasoning' | 'writing' | 'code' | 'vision' | 'general';

export type SpeedTier = 'instant' | 'fast' | 'standard' | 'slow';

export interface FreeTierLimits {
  rpm: number;
  tpm: number;
  rpd: number;
}

export interface ModelCapabilityEntry {
  provider: string;
  display_name: string;
  capabilities: Cap[];
  context_window: number;
  input_price: number;
  output_price: number;
  speed: SpeedTier;
  free_tier: FreeTierLimits | null;
  task_affinity: Partial<Record<TaskType, number>>;
  min_ram_gb?: number;
  min_vram_gb?: number;
  ollama_tag?: string;
}

export const STATIC_REGISTRY: Record<string, ModelCapabilityEntry> = {
  // ===================== OpenAI =====================
  'gpt-4o': {
    provider: 'openai',
    display_name: 'GPT-4o',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION, CAPS.REASONING, CAPS.FUNCTION],
    context_window: 128_000,
    input_price: 2.50,
    output_price: 10.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { general: 1, reasoning: 0.9, code: 0.85, vision: 0.9, writing: 0.8 },
  },
  'gpt-4o-mini': {
    provider: 'openai',
    display_name: 'GPT-4o Mini',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION, CAPS.FUNCTION, CAPS.FAST, CAPS.FREE],
    context_window: 128_000,
    input_price: 0.15,
    output_price: 0.60,
    speed: 'fast',
    free_tier: { rpm: 10, tpm: 100_000, rpd: 1_000_000 },
    task_affinity: { general: 1, code: 0.7, vision: 0.7, writing: 0.7 },
  },
  'o1-preview': {
    provider: 'openai',
    display_name: 'o1-preview',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.REASONING, CAPS.LONG_CONTEXT],
    context_window: 128_000,
    input_price: 15.00,
    output_price: 60.00,
    speed: 'slow',
    free_tier: null,
    task_affinity: { reasoning: 1, code: 0.95, research: 0.9 },
  },
  'o1-mini': {
    provider: 'openai',
    display_name: 'o1-mini',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.REASONING],
    context_window: 128_000,
    input_price: 3.00,
    output_price: 12.00,
    speed: 'slow',
    free_tier: null,
    task_affinity: { reasoning: 0.9, code: 0.85 },
  },
  'gpt-4-turbo': {
    provider: 'openai',
    display_name: 'GPT-4 Turbo',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION, CAPS.FUNCTION],
    context_window: 128_000,
    input_price: 10.00,
    output_price: 30.00,
    speed: 'standard',
    free_tier: null,
    task_affinity: { general: 0.9, code: 0.8, vision: 0.8 },
  },
  'gpt-3.5-turbo': {
    provider: 'openai',
    display_name: 'GPT-3.5 Turbo',
    capabilities: [CAPS.CHAT, CAPS.FUNCTION, CAPS.FAST, CAPS.FREE],
    context_window: 16_385,
    input_price: 0.50,
    output_price: 1.50,
    speed: 'fast',
    free_tier: { rpm: 20, tpm: 200_000, rpd: 2_000_000 },
    task_affinity: { writing: 0.6, general: 0.5 },
  },
  'text-embedding-3-small': {
    provider: 'openai',
    display_name: 'Text Embedding 3 Small',
    capabilities: [CAPS.EMBEDDING, CAPS.FAST, CAPS.FREE],
    context_window: 8191,
    input_price: 0.02,
    output_price: 0.00,
    speed: 'fast',
    free_tier: { rpm: 30, tpm: 300_000, rpd: 3_000_000 },
    task_affinity: { general: 1 },
  },
  'text-embedding-3-large': {
    provider: 'openai',
    display_name: 'Text Embedding 3 Large',
    capabilities: [CAPS.EMBEDDING],
    context_window: 8191,
    input_price: 0.13,
    output_price: 0.00,
    speed: 'standard',
    free_tier: null,
    task_affinity: { general: 1 },
  },
  'dall-e-3': {
    provider: 'openai',
    display_name: 'DALL-E 3',
    capabilities: [CAPS.IMAGE_GEN],
    context_window: 0,
    input_price: 0.04,
    output_price: 0.08,
    speed: 'slow',
    free_tier: null,
    task_affinity: { general: 1 },
  },
  'whisper-1': {
    provider: 'openai',
    display_name: 'Whisper',
    capabilities: [CAPS.AUDIO, CAPS.FAST],
    context_window: 0,
    input_price: 0.006,
    output_price: 0.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { general: 1 },
  },
  'tts-1': {
    provider: 'openai',
    display_name: 'TTS-1',
    capabilities: [CAPS.AUDIO, CAPS.FAST],
    context_window: 0,
    input_price: 0.015,
    output_price: 0.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { general: 1 },
  },

  // ===================== Anthropic =====================
  'claude-opus-4-6': {
    provider: 'anthropic',
    display_name: 'Claude Opus 4',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.REASONING, CAPS.LONG_CONTEXT, CAPS.VISION],
    context_window: 200_000,
    input_price: 15.00,
    output_price: 75.00,
    speed: 'standard',
    free_tier: null,
    task_affinity: { reasoning: 1, research: 0.95, code: 0.9, vision: 0.85 },
  },
  'claude-sonnet-4-6': {
    provider: 'anthropic',
    display_name: 'Claude Sonnet 4',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION, CAPS.REASONING],
    context_window: 200_000,
    input_price: 3.00,
    output_price: 15.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { code: 1, reasoning: 0.85, vision: 0.8 },
  },
  'claude-haiku-4-5-20251001': {
    provider: 'anthropic',
    display_name: 'Claude Haiku 3.5',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION, CAPS.FAST, CAPS.FREE],
    context_window: 200_000,
    input_price: 0.80,
    output_price: 4.00,
    speed: 'fast',
    free_tier: { rpm: 5, tpm: 50_000, rpd: 500_000 },
    task_affinity: { code: 1, general: 0.8, vision: 0.7 },
  },
  'claude-3-5-sonnet-20241022': {
    provider: 'anthropic',
    display_name: 'Claude 3.5 Sonnet',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION],
    context_window: 200_000,
    input_price: 3.00,
    output_price: 15.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { code: 0.95, vision: 0.8, general: 0.7 },
  },
  'claude-3-haiku-20240307': {
    provider: 'anthropic',
    display_name: 'Claude 3 Haiku',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION, CAPS.FAST],
    context_window: 200_000,
    input_price: 0.25,
    output_price: 1.25,
    speed: 'fast',
    free_tier: null,
    task_affinity: { code: 0.8, general: 0.7, vision: 0.6 },
  },
  'claude-3-opus-20240229': {
    provider: 'anthropic',
    display_name: 'Claude 3 Opus',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.REASONING, CAPS.VISION],
    context_window: 200_000,
    input_price: 15.00,
    output_price: 75.00,
    speed: 'standard',
    free_tier: null,
    task_affinity: { reasoning: 1, code: 0.8, vision: 0.8 },
  },

  // ===================== Google / Gemini =====================
  'gemini-2.0-flash': {
    provider: 'google',
    display_name: 'Gemini 2.0 Flash',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION, CAPS.FAST, CAPS.FREE, CAPS.LONG_CONTEXT],
    context_window: 1_048_576,
    input_price: 0.10,
    output_price: 0.40,
    speed: 'fast',
    free_tier: { rpm: 10, tpm: 1_000_000, rpd: 1_500 },
    task_affinity: { general: 1, code: 0.7, vision: 0.7, writing: 0.6 },
  },
  'gemini-1.5-pro': {
    provider: 'google',
    display_name: 'Gemini 1.5 Pro',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION, CAPS.REASONING, CAPS.LONG_CONTEXT],
    context_window: 2_097_152,
    input_price: 1.25,
    output_price: 5.00,
    speed: 'standard',
    free_tier: null,
    task_affinity: { reasoning: 0.9, research: 0.85, code: 0.8, vision: 0.8 },
  },
  'gemini-1.5-flash': {
    provider: 'google',
    display_name: 'Gemini 1.5 Flash',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.VISION, CAPS.FAST],
    context_window: 1_048_576,
    input_price: 0.075,
    output_price: 0.30,
    speed: 'fast',
    free_tier: null,
    task_affinity: { general: 0.8, vision: 0.7, writing: 0.7 },
  },

  // ===================== Mistral =====================
  'mistral-large-latest': {
    provider: 'mistral',
    display_name: 'Mistral Large',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.REASONING, CAPS.FUNCTION],
    context_window: 128_000,
    input_price: 2.00,
    output_price: 6.00,
    speed: 'standard',
    free_tier: null,
    task_affinity: { reasoning: 0.9, code: 0.85 },
  },
  'mistral-small-latest': {
    provider: 'mistral',
    display_name: 'Mistral Small',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.FAST],
    context_window: 32_000,
    input_price: 0.60,
    output_price: 2.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { code: 0.7, general: 0.6 },
  },
  'mistral-embed': {
    provider: 'mistral',
    display_name: 'Mistral Embed',
    capabilities: [CAPS.EMBEDDING, CAPS.FAST],
    context_window: 8192,
    input_price: 0.10,
    output_price: 0.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { general: 1 },
  },

  // ===================== Cohere =====================
  'command-r-plus': {
    provider: 'cohere',
    display_name: 'Command R+',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.REASONING, CAPS.LONG_CONTEXT],
    context_window: 128_000,
    input_price: 3.00,
    output_price: 15.00,
    speed: 'standard',
    free_tier: null,
    task_affinity: { reasoning: 0.8, code: 0.7 },
  },
  'command-r': {
    provider: 'cohere',
    display_name: 'Command R',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.LONG_CONTEXT],
    context_window: 128_000,
    input_price: 0.50,
    output_price: 1.50,
    speed: 'standard',
    free_tier: null,
    task_affinity: { writing: 0.7, code: 0.6 },
  },
  'embed-english-v3.0': {
    provider: 'cohere',
    display_name: 'Embed English v3',
    capabilities: [CAPS.EMBEDDING, CAPS.FAST],
    context_window: 512,
    input_price: 0.10,
    output_price: 0.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { general: 1 },
  },

  // ===================== Groq =====================
  'llama-3.1-70b-versatile': {
    provider: 'groq',
    display_name: 'Llama 3.1 70B',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.FAST, CAPS.FREE, CAPS.LONG_CONTEXT],
    context_window: 131_072,
    input_price: 0.59,
    output_price: 0.79,
    speed: 'fast',
    free_tier: { rpm: 30, tpm: 15_000, rpd: 1_000 },
    task_affinity: { code: 0.8, general: 0.7, writing: 0.6 },
  },
  'llama-3.1-8b-instant': {
    provider: 'groq',
    display_name: 'Llama 3.1 8B',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.FAST, CAPS.FREE],
    context_window: 131_072,
    input_price: 0.05,
    output_price: 0.08,
    speed: 'instant',
    free_tier: { rpm: 30, tpm: 15_000, rpd: 1_000 },
    task_affinity: { general: 0.6, code: 0.5 },
  },
  'mixtral-8x7b-32768': {
    provider: 'groq',
    display_name: 'Mixtral 8x7B',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.FAST, CAPS.FREE],
    context_window: 32_768,
    input_price: 0.24,
    output_price: 0.24,
    speed: 'fast',
    free_tier: { rpm: 30, tpm: 15_000, rpd: 1_000 },
    task_affinity: { code: 0.6, general: 0.5 },
  },

  // ===================== Together AI =====================
  'llama-3.1-70b': {
    provider: 'together',
    display_name: 'Llama 3.1 70B (Together)',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.LONG_CONTEXT],
    context_window: 131_072,
    input_price: 0.59,
    output_price: 0.79,
    speed: 'standard',
    free_tier: null,
    task_affinity: { code: 0.8, general: 0.7 },
  },
  'llama-3.1-8b': {
    provider: 'together',
    display_name: 'Llama 3.1 8B (Together)',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.FAST],
    context_window: 131_072,
    input_price: 0.18,
    output_price: 0.18,
    speed: 'fast',
    free_tier: null,
    task_affinity: { general: 0.6, code: 0.5 },
  },
  'deepseek-chat': {
    provider: 'together',
    display_name: 'DeepSeek Chat',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.LONG_CONTEXT],
    context_window: 128_000,
    input_price: 0.14,
    output_price: 0.28,
    speed: 'standard',
    free_tier: null,
    task_affinity: { code: 0.7, general: 0.6 },
  },

  // ===================== Ollama (Local) =====================
  'ollama-llama3.1-8b': {
    provider: 'ollama',
    display_name: 'Llama 3.1 8B (Local)',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.FAST, CAPS.FREE],
    context_window: 8192,
    input_price: 0.00,
    output_price: 0.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { general: 0.6, code: 0.5 },
    min_ram_gb: 8,
    min_vram_gb: 4,
    ollama_tag: 'llama3.1:8b',
  },
  'ollama-mistral-7b': {
    provider: 'ollama',
    display_name: 'Mistral 7B (Local)',
    capabilities: [CAPS.CHAT, CAPS.CODE, CAPS.FAST, CAPS.FREE],
    context_window: 8192,
    input_price: 0.00,
    output_price: 0.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { code: 0.5, general: 0.5 },
    min_ram_gb: 8,
    min_vram_gb: 4,
    ollama_tag: 'mistral:7b',
  },
  'ollama-nomic-embed-text': {
    provider: 'ollama',
    display_name: 'Nomic Embed Text (Local)',
    capabilities: [CAPS.EMBEDDING, CAPS.FAST, CAPS.FREE],
    context_window: 8192,
    input_price: 0.00,
    output_price: 0.00,
    speed: 'fast',
    free_tier: null,
    task_affinity: { general: 1 },
    min_ram_gb: 4,
    min_vram_gb: 2,
    ollama_tag: 'nomic-embed-text',
  },
};